### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by AlexKuhnle**
- New symbols for graph cigar string: 'M' for matches, 'N' for undefined positions, 'X' for mismatches.
- Improved graph alignment traceback (gssw_alignment_trace_back_*, gssw_graph_trace_back): For some alignments the cigar string didn't correspond to the alignment score, e.g. perfect alignment, but 70% of the sequence softclipped. It still does not work perfectly, then the score is -1 (line 1210).
- Print graph alignment methods output FILE added as argument (gssw_print_graph_mapping, gssw_print_graph_cigar, gssw_print_cigar).
- Header file, examples, etc require changes accordingly.

### CODE REVIEW

**Comment by ekg** [comment]
Hi @AlexKuhnle, have you been testing gssw in vg? If so, do you know how these changes might affect integration? We could also add tests on that end to ensure that the desired behavior is achieved for the tests where you found these issues.

I am in particular interested in the alignment score/cigar mismatch. Do you have an example of this?

**Comment by AlexKuhnle** [comment]
Hi Erik, 

```
I have attached a C file which, once compiled, is a command line tool
```

which constructs a graph and aligns the arguments, all based on gssw.
Below are three example reads where the mentioned problem occurs (old)
and how the situation improves (new). The latter two reads are
overlapping, and it can be seen how they both crash at the same
deletion. The new version solves many cases, although some still exist
(but now get a -1 score, see the corresponding line I gave in the
code). 

```
> ./graph.old
```

GCCGAGATCACGCCACTGTACTCCAGCCTGGACGATATAGTGAGACTTCACCTCAAAAAAAAAAAAAAAAAAAGGAAGTGAGGATTTTAAGACCCTGAGA
TAGTTCTTTTGTGTAAAGCGGTGATTTCTTCCATGGAGGGAATGGTATTTAGGCAATTTTTTTTTTTTTCGAGATGGAGTCTTGCTCTGTCGCTCAGGCT
TGGAACCTTAAGGCTTGTCCCTTTCTAGTTCTTTTGTGTAAAGCGGTGATTTCTTCCATGGAGGGAATGGTATTTAGGCAATTTTTTTTTTTTTCGAGAT

195@16:2[70S30M]
190@15:9[70S30M]
190@15:9[95S5M] [1] 

```
> ./graph.new
```

GCCGAGATCACGCCACTGTACTCCAGCCTGGACGATATAGTGAGACTTCACCTCAAAAAAAAAAAAAAAAAAAGGAAGTGAGGATTTTAAGACCCTGAGA
TAGTTCTTTTGTGTAAAGCGGTGATTTCTTCCATGGAGGGAATGGTATTTAGGCAATTTTTTTTTTTTTCGAGATGGAGTCTTGCTCTGTCGCTCAGGCT
TGGAACCTTAAGGCTTGTCCCTTTCTAGTTCTTTTGTGTAAAGCGGTGATTTCTTCCATGGAGGGAATGGTATTTAGGCAATTTTTTTTTTTTTCGAGAT

195@2614:0[54M]2[14M1X31M]
190@8053:7[56M]9[1D44M]
190@8028:7[81M]9[1D19M] 

```
Let me know if you can verify these findings. 

I am currently doing an internship at Illumina in Chesterford,
```

supervised by Nondas Fritzilas and Peter Krusche (whom, I think, you
know), where I investigated graph sequences and made a tool,
basically, for constructing graphs, which wasn't possible with VG
since it requires fasta+vcf. The graph sequence was then "converted"
to GSSW and reads were aligned to an executable similar as above.
Unfortunately, this internship ends today, when we decided to push
this modification, so I fear it won't be easily possible to provide
examples from today on. 

```
And by the way: Great work with GSSW and VG! 

Best regards, 

Alex 

-----Original-Nachricht----- 

Betreff: Re: [gssw] Corrections (#1) 

Datum: Fri, 02 Oct 2015 11:10:32 +0200 

Von: Erik Garrison <notifications@github.com> 

An: ekg/gssw <gssw@noreply.github.com> 

Hi @AlexKuhnle [2], have you been testing gssw in vg? If so, do you
```

know how these changes might affect integration? We could also add
tests on that end to ensure that the desired behavior is achieved for
the tests where you found these issues. 

```
I am in particular interested in the alignment score/cigar mismatch.
```

Do you have an example of this? 

```
—
```

Reply to this email directly or view it on GitHub [3].

## Links:

[1] mailto:190@15:9[95S5M]
[2] https://github.com/AlexKuhnle
[3] https://github.com/ekg/gssw/pull/1#issuecomment-144966167

**Comment by ekg** [comment]
Hi @AlexKuhnle, I'm not sure if I see the attachment. Would you please try to attach it again to this issue?

Thank you very much for your help with gssw! The debugging help is much appreciated, and I'm sad to hear that you are finishing your internship today. I hope you have the opportunity to continue contributing even if not with Illumina.

> I investigated graph sequences and made a tool, basically, for constructing graphs, which wasn't possible with VG since it requires fasta+vcf

I'm not sure if this was all true when you started your internship, but at present vg can take any of the following inputs to generate a graph:
- fasta + VCF (`vg construct`)
- fasta (`vg msga`) --- the sequences are assembled using progressive partial order alignment
- a graph + alignments against it (`vg mod` and `vg msga`)
- an assembly graph in GFA format (`vg view`)

I'm always curious about other ways we might get data into this space. Will you release your gssw-based tool as well?

Again, thanks for the help, and have a nice fall!

**Comment by AlexKuhnle** [comment]
Hi Erik,

it seems that Github doesn't allow me to attach it on the website itself ("Something went really wrong, and we can’t process that file."), and attaching it in a mail seemed to have also not worked. Can you give me your mail address, then I will send it to you.
The msga feature indeed didn't exist then, but I saw that it was integrated later. For my project I focused on creating graphs from MSAs, so similar to the msga mode. However, I think that if one starts from a given complete MSA, one looks slightly different on the problem of graph construction as opposed to the iterative construction of msga. Don't know whether it would have made a big difference for my experimental investigations...
We are thinking about publishing the tool and results, but right now it's not in an appropriate state yet, and everything first needs to be a bit more refined.

Alex

**Comment by ekg** [comment]
erik.garrison@gmail.com

**Pull request closed without merging**
